config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'operators#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :operators
  resources :sessions, :only => [:new, :create, :destroy]
  resources :tickets, :except => [:update, :destroy]
  resources :tickets_types, :only => [:new, :create]
  resources :statuses
  resources :departments
   
  root to: "tickets#new"
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :authorize

  def index
    @statuses = Status.all

    respond_to do |format|
      format.html
      format.json { render json: @statuses }
    end
  end

  def new
    @status = Status.new

    respond_to do |format|
      format.html
      format.json { render json: @status }
    end
  end

  def edit
    @status = Status.find(params[:id])
  end

  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to statuses_url, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to statuses_url, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.haml
= simple_form_for(@status) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title

  .form-actions
    = f.button :submit

app/views/statuses/edit.html.haml
%h1 Editing status

= render 'form'

= link_to 'show', @status
\|
= link_to 'back', statuses_path

app/views/statuses/index.html.haml
%h1 Listing statuses

%table.table.table-hover.table-striped.table-bordered
  %tr
    %th #
    %th Title
    %th
    %th
    %th

  - @statuses.each do |status|
    %tr
      %td= status.id
      %td= status.title
      %td= link_to 'show', status
      %td= link_to 'edit', edit_status_path(status)
      %td= link_to 'destroy', status, :method => :delete, :data => { :confirm => 'are you sure?' }

%br

= link_to 'new status', new_status_path

app/views/statuses/new.html.haml
%h1 New status

= render 'form'

= link_to 'back', statuses_path