config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'operators#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :operators
  resources :sessions, :only => [:new, :create, :destroy]
  resources :tickets, :except => [:update, :destroy]
  resources :tickets_types, :only => [:new, :create]
  resources :statuses
  resources :departments
   
  root to: "tickets#new"
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  has_secure_password

  attr_accessible :name, :email, :password, :password_confirmation
  
  validates :email, presence: true, 
                    uniqueness: true,
                    length: { minimum: 8, maximum: 50}

end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  before_action :authorize, except: [:new, :create]

  def index
    @operators = Operator.all

    respond_to do |format|
      format.html
      format.json { render json: @operators }
    end
  end

  def new
    @operator = Operator.new

    respond_to do |format|
      format.html
      format.json { render json: @operator }
    end
  end

  def edit
    @operator = Operator.find(params[:id])
  end

  def create
    @operator = Operator.new(params[:operator])

    respond_to do |format|
      if @operator.save
        format.html { redirect_to operators_url, notice: 'Operator was successfully created.' }
        format.json { render json: @operator, status: :created, location: @operator }
      else
        format.html { render action: "new" }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @operator = Operator.find(params[:id])

    respond_to do |format|
      if @operator.update_attributes(params[:operator])
        format.html { redirect_to operators_url, notice: 'Operator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @operator = Operator.find(params[:id])
    @operator.destroy

    respond_to do |format|
      format.html { redirect_to operators_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/views/operators/_form.html.haml
= simple_form_for(@operator) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit

app/views/operators/edit.html.haml
%h1 Editing operator

= render 'form'

= link_to 'show', @operator
\|
= link_to 'back', operators_path

app/views/operators/index.html.haml
%h1 Listing operators

%table.table.table-hover.table-striped.table-bordered
  %tr
    %th #
    %th Name
    %th Email
    %th
    %th
    %th

  - @operators.each do |operator|
    %tr{class: (current_user && operator.id == current_user.id) && 'success'}
      %td= operator.id
      %td= operator.name
      %td= operator.email
      %td= link_to 'show', operator
      %td= link_to 'edit', edit_operator_path(operator)
      %td= link_to 'destroy', operator, :method => :delete, :data => { :confirm => 'are you sure?' }

%br

= link_to 'new operator', new_operator_path

app/views/operators/new.html.haml
%h1 New operator

= render 'form'

= link_to 'back', operators_path