config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'operators#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :operators
  resources :sessions, :only => [:new, :create, :destroy]
  resources :tickets, :except => [:update, :destroy]
  resources :tickets_types, :only => [:new, :create]
  resources :statuses
  resources :departments
   
  root to: "tickets#new"
end

app/views/shared/_flash.haml
- if notice || alert
  .row-fluid
    .span12
      - if notice
        %div{:class => "alert alert-success"}
          %a.close{:href => "#", data: { dismiss: :alert } }  ×
          = notice

      - if alert
        %div{:class => "alert"}
          %a.close{:href => "#", data: { dismiss: :alert } } ×
          = alert

app/views/shared/_navigation.haml
.navbar.navbar-static-top
  .navbar-inner
    .container
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
        %span.icon-th-list
      %a.brand{ href: '/' } SITS
      .nav-collapse
        %ul.nav
          %li{class: request.path == new_ticket_path && 'active'}= link_to "new ticket", new_ticket_path
        %ul.nav.pull-right
          - if current_user
            %li{class: request.path == tickets_path && 'active'}= link_to "tickets", tickets_path
            %li{class: request.path == operators_path && 'active'}= link_to "operators", operators_path
            %li{class: request.path == departments_path && 'active'}= link_to "departments", departments_path
            %li{class: request.path == statuses_path && 'active'}= link_to "statuses", statuses_path
            %li.divider-vertical
            %li= link_to "log out", '/logout'
          - else
            %li= link_to "log in", '/login'
            %li= link_to "sign up", '/signup'