config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'operators#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :operators
  resources :sessions, :only => [:new, :create, :destroy]
  resources :tickets, :except => [:update, :destroy]
  resources :tickets_types, :only => [:new, :create]
  resources :statuses
  resources :departments
   
  root to: "tickets#new"
end

app/models/department.rb
class Department < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authorize

  def index
    @departments = Department.all

    respond_to do |format|
      format.html
      format.json { render json: @departments }
    end
  end

  def new
    @department = Department.new

    respond_to do |format|
      format.html 
      format.json { render json: @department }
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to departments_url, notice: 'Department was successfully created.' }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to departments_url, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.haml
= simple_form_for(@department) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/departments/edit.html.haml
%h1 Editing department

= render 'form'

= link_to 'show', @department
\|
= link_to 'back', departments_path

app/views/departments/index.html.haml
%h1 Listing departments

%table.table.table-hover.table-striped.table-bordered
  %tr
    %th #
    %th Name
    %th
    %th
    %th

  - @departments.each do |department|
    %tr
      %td= department.id
      %td= department.name
      %td= link_to 'show', department
      %td= link_to 'edit', edit_department_path(department)
      %td= link_to 'destroy', department, :method => :delete, :data => { :confirm => 'are you sure?' }

%br

= link_to 'new department', new_department_path

app/views/departments/new.html.haml
%h1 New department

= render 'form'

= link_to 'back', departments_path